name: Makefile CI

on:
  push:
    branches: [ "main", "ci" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps

    - name: Run Linux build
      run: make build_linux

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: script-creator-linux
        path: script_creator_-*.bin
